motion_config: !include factory/components/motion_configs/right_fr3_with_pika_ati_ik.yaml
max_step_nums: 150 # for gym steps
is_debug: false

task_data_dir: "dataset/data/0109_duo_unitree_tube_insert_human_282ep"
data_type: "human_hand"
action_prediction_step: 2
skip_steps: 2
# end_effector_pose_delta
action_type: "end_effector_pose"
action_orientation_type: "quaternion"
observation_type: "ee_pose"
contain_ft: false
use_relative_pose: true
state_keys: ["right"]
cam_keys: ["right_hand_color", "right_hand_fisheye_color"]
rotation_transform: 
  right: [0.7071068, 0, 0.7071068, 0]

replay_frequency: 30
tool_position_dof: 1
tool_max: 1.0
enable_hardware: false

# move to start position for pick n place
# cartesian
# reset_arm_command: [0.21374957, -0.38555737,  0.39685211, 0.97728997, -0.01475875,  0.20979072,  0.02596818]
# reset_space: "cartesian"
# reset_arm_command: [-0.0401738194832479, -1.5299874232993738, -1.9312359323737118, -2.4809956539881894, 0.0536879692413298, 2.5041080054362572, -1.2317390192072197]
reset_arm_command: [0.5, -0.35, 0.135026055, 0.7071068, 0, 0.7071068, 0]
reset_space: "cartesian"
reset_arm_to_default: true
