motion_config: !include factory/components/motion_configs/unitree_g1_upper.yaml
max_step_nums: 150 # for gym steps
is_debug: false

task_data_dir: "dataset/data/1207_duo_unitree_pick_n_place_194ep"
action_prediction_step: 2
skip_steps: 3
# end_effector_pose_delta
action_type: "end_effector_pose"
action_orientation_type: "quaternion"
observation_type: "ee_pose"
contain_ft: false
use_relative_pose: true
contain_head: true
state_keys: ["left", "right", "head"]
rotation_transform: 
  left: [0, 0, 0, 1]
  right: [0, 0, 0, 1]
  head: [0, 0, 0, 1]

replay_frequency: 30
tool_position_dof: 1
tool_max: 1.0
enable_hardware: false

# move to start position for pick n place
# cartesian
# reset_arm_command: [0.21374957, -0.38555737,  0.39685211, 0.97728997, -0.01475875,  0.20979072,  0.02596818]
# reset_space: "cartesian"
reset_space: "joint"
