motion_config: !include factory/components/motion_configs/fr3_with_hand_impedance.yaml

teleop_interface: "space_mouse"
interface_config: !include teleop/space_mouse/single_space_mouse_cfg.yaml
inteface_output_mode: "relative"

target_site_name: ["target_site"]
tcp_visualization_site: ["TCP_site"]

# teleoperation used parameter
# if you are using mujoco simulation target instead of teleoperation device,
# set use_simulation_target as true
use_simulation_target: false
teleoperation_loop_time: 0.005

reset_arm_command: [3.69019823e-01,  1.99873044e-04,  3.64437265e-01,  9.99989858e-01,
                    -2.65401198e-03, -1.43284955e-03,  3.34460145e-03]
reset_space: "cartesian"
