ros2_camera:
  image_shape: [480, 640]
  fps: 15
  # ROS2 topic names for different data streams
  image_topic: "/left/color/image_raw"
  depth_topic: "/left/depth/image_raw" 
  serial_number: "CP769450002G"

  # Data capabilities
  contain_depth: false
  contain_imu: false

