# gym
max_step_nums: 150
action_type: "joint_position"
action_orientation_type: "quat"
obs_contain_ee: false
num_episodes: 10
is_debug: false
reset_space: "joint"
execution_step: 10
display_window_name: "pi0 inference"

# @TODO: update config, "pi0_hirol_pick_N_place_abs_jps_side" "pi0_hirol_fr3_peg_in_hole_abs_jps" "pi0_hirol_pick_N_place_abs_jps_side_mix"
# "pi05_hirol_fr3_block_stacking_abs_jps" "pi05_hirol_fr3_pick_n_place" "pi05_hirol_fr3_peg_in_hole_abs_jps"
model_cfg_name: "pi0_hirol_pick_N_place_abs_jps_side_mix"

# model_dir: "/home/yuxuan/Code/hirol/checkpoints/pi0/fr3/0910/pi0_hirol_pick_N_place_abs_jps_side/40000"
# model_dir: "/home/yuxuan/Code/hirol/checkpoints/pi0/fr3/0915/pi05_block_stacking/29999"
# model_dir: "/home/yuxuan/Code/hirol/checkpoints/pi0/fr3/0915/pi05_pick_n_place_side/30000"
# model_dir: "/home/yuxuan/Code/hirol/checkpoints/pi0/fr3/0910/pi0_peg_in_hole_abs_jps/29999"
model_dir: "/home/yuxuan/Code/hirol/checkpoints/pi0/fr3/0910/pi0_pick_N_place_abs_jps_mix/49999"

# tasks:  ["description: pick up the peg on the table and put it in the hole stpes: step1: find the peg on the table. step2: go to the location of the peg step3: pick up the obly peg on the table. stpe4: find the only hole in the peg station. step5: go to the top of the hole. step6: place the peg into the hole goal: pick up the peg on the table and place it in the correct hole",
#         ]
tasks: ["description: picking up the kiwi from the table to the container steps: step1: locate the container and the kiwi on the table. step2: grab the kiwi from the table. step3: go to the location of the container. step4: place the kiwi into the container. goal: successfully pick up the kiwi from the table to the container"]
# tasks: ["description: stack colored blocks in the order: red -> green -> blue -> yellow steps:  step1: locate the red block on the table. step5: locate the blue block on the table. step6: pick up the blue block and place it on top of the red block. step7: locate the yellow block on the table. step8: pick up the yellow block and place it on top of the blue block. step9: verify the tower is stable with the order: red -> blue -> yellow. goal: build a tower by stacking blocks in the correct color sequence"]

# robot + motion factory
motion_config: !include factory/components/motion_configs/fr3_with_franka_hand_ik.yaml
