pika_tracker:
  serial_ports: 
    left: "/dev/ttyUSB71"
    right: null
  target_device: 
    left: "LHR-0DFD738C" 
    right: null
  output_left: true
  output_right: false
  init_pose:
    initial_pose_left: [0, 0, 0, 1, 0, 0, 0]
    initial_pose_right: [0, 0, 0, 1, 0, 0, 0]
  rotation_enabled:
    # rpy
    left: [false, false, true]
    right: null
