pika_tracker:
  serial_ports: 
    left: "/dev/ttyUSB0"
    right: null
  target_device: 
    # LHR-0DFD738C
    left: "LHR-5EC33B35" 
    right: null
  output_left: true
  output_right: false
  init_pose:
    initial_pose_left: [0, 0, 0, 0, 0, 0, 1]
    initial_pose_right: [0, 0, 0, 0, 0, 0, 1]
