pika_tracker:
  serial_ports: 
    left: "/dev/ttyUSB71"
    right: "/dev/ttyUSB70"
  target_device: 
    left: "LHR-B8FF68EC"
    right: "LHR-5EC33B35"
  output_left: true
  output_right: true
  init_pose:
    # @TODO: 对齐初始化状态
    initial_pose_left: [0, 0, 0, 0, 0, 0, 1]
    initial_pose_right: [0, 0, 0, 0, 0, 0, 1]
  rotation_enabled:
    # rpy
    left: [false, false, true]
    right: [false, false, true]

