pika_tracker:
  serial_ports: 
    left: "/dev/ttyUSB71"
    right: "/dev/ttyUSB70"
  target_device: 
    left: "LHR-5EC33B35"
    right: "LHR-0DFD738C" 
  output_left: true
  output_right: true
  init_pose:
    initial_pose_left: [0, 0, 0, 0, 0, 0, 1]
    initial_pose_right: [0, 0, 0, 0, 0, 0, 1]
