pika_tracker:
  serial_ports: 
    left: null
    right: "/dev/ttyUSB70"
  target_device: 
    left: null
    right: "LHR-5EC33B35" 
  output_left: false
  output_right: true
  init_pose:
    initial_pose_left: [0, 0, 0, 0, 0, 0, 1]
    initial_pose_right: [0, 0, 0, 0, 0, 0, 1]
  rotation_enabled:
    # rpy
    left: null
    right: [false, false, true]
