name: hirol_fr3_abs_jps_ee_state_lerobot_v3

image_shape: &image_shape [3, 480, 640]
shape_meta: &shape_meta
  obs:
    ee_cam_color:
      shape: *image_shape
      type: rgb
    third_person_cam_color:
      shape: *image_shape
      type: rgb
    side_cam_color:
      shape: *image_shape
      type: rgb
    state:
      shape: [15]
      type: low_dim
      components:
        ee_position: [0, 3]
        ee_quaternion: [3, 7]
        joint_positions: [7, 14]
        gripper_width: [14, 15]
  action:
    shape: [8]
    min: [-2.96, -1.76, -2.96, -3.07, -2.96, -2.09, -2.96, 0.0]
    max: [2.96, 1.76, 2.96, -0.07, 2.96, 3.75, 2.96, 0.08]

env_runner:
  _target_: diffusion_policy.env_runner.hirol_fr3_runner.HirolFr3Runner
  test_start_seed: 100000

dataset:
  _target_: diffusion_policy.dataset.hirol_lerobot_v3_dataset.HirolLeRobotV3Dataset
  shape_meta: *shape_meta
  dataset_path: ${dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null
  window_sampling_strategy: idx
  image_feature_map:
    ee_cam_color: observation.images.ee_cam_color
    third_person_cam_color: observation.images.third_person_cam_color
    side_cam_color: observation.images.side_cam_color
  lowdim_feature_groups:
    state:
      - observation.state
  action_feature_fields:
    - action
  timestamp_key: timestamp
  timestamp_step_sec: null
  timestamp_tolerance_sec: null
  local_files_only: true
