urdf_path: "assets/unitree_g1/g1_29dof_with_hand.urdf"
mesh_offset: "assets/unitree_g1"
# ignore hand
frames: ["pelvis", "left_ankle_pitch_link", "right_ankle_pitch_link",
        "torso_link", "left_hand_palm_link", "right_hand_palm_link",
        "left_hand_thumb_2_link", "left_hand_middle_1_link",
        "left_hand_index_1_link", "right_hand_thumb_2_link",
        "right_hand_middle_1_link", "right_hand_index_1_link"]
# maybe we need to lock the hand related joint
base_link: "pelvis"
ee_link: ["left_hand_palm_link", "right_hand_palm_link", "left_ankle_pitch_link", "right_ankle_pitch_link"]
fixed_base: true
lock_joints:
  - base: "left_hand_palm_link"
    end: "left_hand_thumb_2_link"
  - base: "left_hand_palm_link"
    end: "left_hand_middle_1_link"
  - base: "left_hand_palm_link"
    end: "left_hand_index_1_link"
  - base: "right_hand_palm_link"
    end: "right_hand_thumb_2_link"
  - base: "right_hand_palm_link"
    end: "right_hand_middle_1_link"
  - base: "right_hand_palm_link"
    end: "right_hand_index_1_link"
  
# not finished
tracking_frames:
  - name: "left_hand_palm_link"
    dim: [4, 4]
    require_trans: true
    trans_scalar: 1.0
    require_rot: true
    rot_scalar: 1.0
  - name: "right_hand_palm_link"
    dim: [4,4]
    require_trans: true
    trans_scalar: 1.0
    require_rot: true
    rot_scalar: 1.0
  - name: "left_ankle_pitch_link"
    dim: [4, 4]
    require_trans: true
    trans_scalar: 1.0
    require_rot: true
    rot_scalar: 1.0
  - name: "right_ankle_pitch_link"
    dim: [4,4]
    require_trans: true
    trans_scalar: 1.0
    require_rot: true
    rot_scalar: 1.0
show_debug: false
trans_weight: 2.0
rot_weight: 1.0
smooth_weight: 0.3
regularization_weight: 0.02

