# xArm API Constants based on xArm Python SDK documentation
# Modes
XARM_MODE_POSITION = 0
XARM_MODE_SERVO = 1
XARM_MODE_TEACHING = 2
XARM_MODE_VELOCITY = 4

# States  
XARM_STATE_SPORT = 0
XARM_STATE_STOP = 3
XARM_STATE_PAUSE = 4

# Return Codes
XARM_SUCCESS = 0
XARM_ERROR = -1

# Motion States
XARM_MOTION_RUNNING = 1
XARM_SLEEPING = 2
XARM_SUSPENDED = 3
XARM_STOPPING = 4

TOOL_TYPE_XARM_GRIPPER = 1
# Unit Conversion
MM_PER_M = 1000  # Convert meters to millimeters

XARM_GRIPPER_MODE_LOCATION = 0

XARM_GRIPPER_MAX_POSITION = 800
XARM_GRIPPER_MAX_POSITION_SIM = 8