name: "unitreeG1"

# urdf_path: "assets/franka_fr3/fr3.urdf"
arm: !include arm.yaml
leg: !include leg.yaml
waist: !include waist.yaml

network_interface: 'lo'
robot_domain: 1

control_dt: 0.002
duration: 3.0
