# task_list: ["block_stacking_fix", "block_stacking_random"]
fps: 30
output_path: "/home/zyx/dataset/dp/fr3/0920"
data_name: "solid_transfer_1_step_0_skip_abs_jps"
action_type: "joint_position"
# action_ori_type: "euler"
action_prediction_step: 1
contain_ee_obs: false

# Parallel processing settings
parallel: true          # Set to true to enable parallel processing
num_processes: 80        # Number of processes to use (null or omit to use all CPU cores)
