# task_list: ["block_stacking_fix", "block_stacking_random"]
fps: 15
output_path: "/home/zyx/dataset/dp/fr3/1020"
data_name: "insert_tube_1_step_2_skip_pose2delPose_euler"
action_type: "end_effector_pose_delta"
action_ori_type: "euler"
action_prediction_step: 1
obs_type: "ee_pose"
contain_ft: false

# Parallel processing settings
parallel: true          # Set to true to enable parallel processing
num_processes: 30        # Number of processes to use (null or omit to use all CPU cores)
