# task_list: ["block_stacking_fix", "block_stacking_random"]
fps: 15
output_path: "/home/zyx/dataset/dp/fr3/1022"
data_name: "pick_n_place_1_step_2_skip_abs_jps"
action_type: "joint_position"
# action_ori_type: "euler"
action_prediction_step: 1
obs_type: "jonit_position"
contain_ft: false

# Parallel processing settings
parallel: true          # Set to true to enable parallel processing
num_processes: 80        # Number of processes to use (null or omit to use all CPU cores)
