.git
.gitignore
.venv
__pycache__
.pytest_cache
.mypy_cache
.ruff_cache
.vscode
.idea

data
outputs
wandb
logs
tmp
media
hirol_dataset
data_converter/dataset
data_converter/output
data_converter/outputs

*.ckpt
*.pt
*.pth
*.npz
*.zarr
*.zarr.zip
*.tar
*.tar.gz
*.zip
*.log

dp.zip
index.html
index.html.1

diffusion_policy.egg-info
build
dist
