urdf_path: "assets/unitree_g1/right_dex3_hand.urdf"
mesh_offset: "assets/unitree_g1"
frames: ["world", "rt_tcp", "rm_tcp", "ri_tcp"]
# maybe we need to lock the hand related joint
base_link: "world"
ee_link: ["rt_tcp", "rm_tcp", "ri_tcp"]
fixed_base: true
