
joint_names: ["fr3_joint1",
        "fr3_joint2",
        "fr3_joint3",
        "fr3_joint4",
        "fr3_joint5",
        "fr3_joint6",
        "fr3_joint7"]
ip: "192.168.1.101"
control_mode: 'position'
urdf_path: "assets/franka_fr3/fr3.urdf"

gripper:
  !include fr3gripper.yaml

# cycle_start
# home_config: [-2.9804, -1.5563, 1.7109, -1.6425, -1.5253, 2.7178]

# base_frame: "base_link"
# flange_frame: "ee_link"
base_link: "base"
end_link: "fr3_hand"
# jvel_limit: [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]
# jacc_limit: [1.57, 1.57, 1.57, 1.57, 1.57, 1.57]
# max_deviation: 0.01