duo_arm:
  dof: [7,7]
  left:
      type: "fr3"
      dof: 7
      ip: "192.168.1.105"
    #   damping: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      stiffness: [400, 400, 400, 400, 100, 100, 50]
      # filter_coeff: None
  right:
      type: "fr3"
      dof: 7
      ip: "192.168.1.208"
    #   damping: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      stiffness: [400, 400, 400, 400, 100, 100, 50]
      # filter_coeff: None
