model:
  urdf_path: "assets/franka_fr3/fr3_only.urdf"
  base_link: "base"
  end_effector_link: "fr3_ee"

"ik": 
  damping_weight: 0.3
  # ["gaussian_newtown", "pyroki"， "dls", "lm"]
  # pyroki 慎用， 关节会有跳变
  ik_type: "gaussian_newtown"
  tolerance: 0.0001
  max_iteration: 1000
