whole_body_ik:
  tracking_frames:
  - name: "left_tcp"
    dim: [4, 4]
    require_trans: true
    trans_scalar: 1.0
    require_rot: true
    rot_scalar: 1.0
  - name: "right_tcp"
    dim: [4,4]
    require_trans: true
    trans_scalar: 1.0
    require_rot: true
    rot_scalar: 1.0
  show_debug: false
  trans_weight: 200
  rot_weight: 85
  smooth_weight: 0.02
  regularization_weight: 0.002
  
  # target_threshold: 0.001
  # rot_target_threshold: 0.001
  # joint_state_threshold: 0.002
  # max_iter: 50
  # solver_tol: 1e-6
  # acceptable_tol: 1e-5

  