mujoco:
  # the file path should be related to the hirol platform folder
  base_xml_file: "assets/unitree_g1/scene_g1_29dof_only_upper.xml"
  robot_xml: "assets/unitree_g1/g1_29dof_only_upper.xml"
  quat_sequence: "xyzw"
  dt: 0.002
  dof: [7, 7]
  joint_names: [
                "left_shoulder_pitch_joint",
                "left_shoulder_roll_joint",
                "left_shoulder_yaw_joint",
                "left_elbow_joint",
                "left_wrist_roll_joint",
                "left_wrist_pitch_joint",
                "left_wrist_yaw_joint",
                "right_shoulder_pitch_joint",
                "right_shoulder_roll_joint",
                "right_shoulder_yaw_joint",
                "right_elbow_joint",
                "right_wrist_roll_joint",
                "right_wrist_pitch_joint",
                "right_wrist_yaw_joint"]
  actuator_names: [
                "left_shoulder_pitch",
                "left_shoulder_roll",
                "left_shoulder_yaw",
                "left_elbow",
                "left_wrist_roll",
                "left_wrist_pitch",
                "left_wrist_yaw",
                "right_shoulder_pitch",
                "right_shoulder_roll",
                "right_shoulder_yaw",
                "right_elbow",
                "right_wrist_roll",
                "right_wrist_pitch",
                "right_wrist_yaw"]
  actuator_mode: ["position", "position", "position", "position", "position", "position", "position",
                  "position", "position", "position", "position", "position", "position", "position",]
  # ee_site_name: "left_hand_site"
  base_body: ["pelvis"]
  extra_render: true
  max_traj_len: 80
  use_custom_key_frame: true
  # sensor_dict:
    # ee_cam: 
    #  resolution: [480, 640]