mujoco:
  # the file path should be related to the hirol platform folder
  base_xml_file: "assets/franka_fr3/fr3_scene.xml"
  robot_xml: "assets/franka_fr3/fr3.xml"
  quat_sequence: "xyzw"
  dt: 0.002
  dof: [7]
  joint_names: ["fr3_joint1", "fr3_joint2", "fr3_joint3", "fr3_joint4", "fr3_joint5", "fr3_joint6", "fr3_joint7"]
  actuator_names: ["fr3_actuator1", "fr3_actuator2", "fr3_actuator3", "fr3_actuator4", "fr3_actuator5", "fr3_actuator6", "fr3_actuator7"]
  actuator_mode: ["torque", "torque", "torque", "torque", "torque", "torque", "torque"]
  ee_site_name: "fr3_ee_attachment"
  extra_render: true
  max_traj_len: 80
  base_body: "base"
  # sensor_dict: None
  use_custom_key_frame: true
  sensor_dict:
    ee_cam: 
     resolution: [480, 640]