mujoco:
  # the file path should be related to the hirol platform folder
  base_xml_file: "assets/monte_01/urdf/scene_monte01.xml"
  robot_xml: "assets/monte_01/urdf/robot_description.xml"
  quat_sequence: "xyzw"
  dt: 0.002
  dof: [7, 7]
  joint_names: [
                "left_arm_joint_1",
                "left_arm_joint_2",
                "left_arm_joint_3",
                "left_arm_joint_4",
                "left_arm_joint_5",
                "left_arm_joint_6",
                "left_arm_joint_7",
                "right_arm_joint_1",
                "right_arm_joint_2",
                "right_arm_joint_3",
                "right_arm_joint_4",
                "right_arm_joint_5",
                "right_arm_joint_6",
                "right_arm_joint_7"]
  # Updated with actual XML actuator names
  actuator_names: [
                  "left_arm_joint_1_ctrl",
                  "left_arm_joint_2_ctrl",
                  "left_arm_joint_3_ctrl",
                  "left_arm_joint_4_ctrl",
                  "left_arm_joint_5_ctrl",
                  "left_arm_joint_6_ctrl",
                  "left_arm_joint_7_ctrl",
                  "right_arm_joint_1_ctrl",
                  "right_arm_joint_2_ctrl",
                  "right_arm_joint_3_ctrl",
                  "right_arm_joint_4_ctrl",
                  "right_arm_joint_5_ctrl",
                  "right_arm_joint_6_ctrl",
                  "right_arm_joint_7_ctrl"]
  actuator_mode: [  
    "position", "position", "position", "position", "position",
                  "position", "position", "position", "position", "position", "position", "position",
                  "position", "position"]
  ee_site_name: "left_tcp" # @TODO: check
  extra_render: true
  max_traj_len: 80
  base_body: ["base_car"]  # Root body in XML is unnamed worldbody
  # sensor_dict: None
  use_custom_key_frame: true
  sensor_dict:
    head_front_cam: 
     resolution: [480, 640] #@TODO support 720p
    left_ee_cam: 
     resolution: [480, 640]
    # right_ee_cam: 
    #  resolution: [480, 640]
     