FROM osrf/ros:humble-desktop-jammy

USER root

COPY sources.list /etc/apt/sources.list

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-desktop-full

# 设置工作目录
WORKDIR /workspace


RUN apt install libnss3-tools

# 安装mkcert
RUN apt-get install -y wget
RUN wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64 -O /usr/local/bin/mkcert
RUN chmod +x /usr/local/bin/mkcert

# 创建证书目录
RUN mkdir -p /workspace/certification

RUN if ! getent group teleophost >/dev/null; then \
    groupadd -g 1000 teleophost || groupadd teleophost; \
    fi

RUN if ! getent passwd teleophost >/dev/null; then \
    useradd -create-home -u 1000 -g teleophost -m teleophost || useradd -create-home -g teleophost -m teleophost; \
    fi

RUN mkdir -p /home/teleophost/.pip
COPY --chown=teleophost pip.conf /home/teleophost/.pip/pip.conf

RUN apt install -y wget zlib1g-dev libssl-dev libncurses5-dev libsqlite3-dev libreadline-dev libtk8.6 libgdm-dev libdb4o-cil-dev libpcap-dev

WORKDIR  /home/teleophost
RUN wget https://mirrors.huaweicloud.com/python/3.8.19/Python-3.8.19.tar.xz && tar -xvf Python-3.8.19.tar.xz
WORKDIR  /home/teleophost/Python-3.8.19

RUN ./configure --prefix=/usr/local && make && make install

WORKDIR /usr/local/bin/
RUN ln -s pip3 pip

RUN rm /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0 /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0.0.0 /usr/share/glvnd/egl_vendor.d/50_mesa.json
COPY ./nvidia_icd.json /usr/share/vulkan/icd.d/nvidia_icd.json
COPY ./10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json

RUN apt-get update && \
    apt-get install -y --no-install-recommends software-properties-common && \
    add-apt-repository universe && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        libxcursor-dev \
        libxrandr-dev \
        libxinerama-dev \
        libxi-dev \
        mesa-common-dev \
        zip \
        unzip \
        make \
        # vulkan-utils \
        mesa-vulkan-drivers \
        pigz \
        git \
        libegl1

RUN apt-get install -y \
        mesa-utils \
        vulkan-tools

RUN apt install -y usbutils vim udev

# 复制项目文件
COPY --chown=teleophost . .

# 生成证书（需要运行时指定实际IP）
# RUN mkcert -install && mkcert -cert-file /workspace/certification/cert.pem -key-file /workspace/certification/key.pem localhost 127.0.0.1 ::1

# 设置环境变量
ENV PYTHONPATH=/app:${PYTHONPATH} \
    ROS_DOMAIN_ID=0

RUN usermod -aG sudo teleophost && echo "teleophost ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER teleophost
RUN pip3 install transforms3d numpy pyyaml opencv-python transformations vuer==0.0.32rc7

    #  \
    # && rm -rf /var/lib/apt/lists/*
########################################### 以上构建出ghcr.io/bigjohnn/quest3-monte03-teleop:v1########################################################

# FROM ghcr.io/bigjohnn/quest3-monte03-teleop:v1


# RUN echo "conda activate tv" >> /home/teleophost/.bashrc
# RUN echo "source /opt/ros/humble/setup.bash" >> /home/teleophost/.bashrc
# WORKDIR /workspace

# RUN http_proxy="" https_proxy="" /home/teleophost/miniconda3/envs/tv/bin/pip install numpy==1.26.4 glog \
# mujoco \
# xarm-python-sdk

# USER root
# RUN usermod -aG input,plugdev,dialout teleophost
# RUN http_proxy="" https_proxy="" apt-get update && http_proxy="" https_proxy="" apt-get install -y libhidapi-dev
# # RUN echo 'KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="plugdev"' > /etc/udev/rules.d/99-hidraw-permissions.rules
# RUN echo 'SUBSYSTEM=="input", GROUP="input", MODE="0660"' > /etc/udev/rules.d/99-hidraw-permissions.rules
# RUN echo 'KERNEL=="hidraw*", ATTRS{idVendor}=="256f", ATTRS{idProduct}=="c635", MODE="0666"' >> /etc/udev/rules.d/99-hidraw-permissions.rules

# USER teleophost

# RUN http_proxy="" https_proxy="" /home/teleophost/miniconda3/envs/tv/bin/pip install pyspacemouse