# gym
max_step_nums: 150
action_type: "joint_position"
action_orientation_type: "quat"
obs_contain_ee: false
num_episodes: 10
is_debug: false
use_hardware: false
reset_space: "joint"
execution_step: 10
display_window_name: "pi0 client inference"
async_execution: false

key_mapping: 
  third_person_cam_color: "observation/exterior_image_1_left"
  ee_cam_color: "observation/wrist_image_left"
  task: "prompt"
  joint_state: "observation/joint_position"
  gripper_state: "observation/gripper_position"

# prompt guidance
# tasks: ["goal: successfully pick up the kiwi from the table to the container"]
# tasks: ["goal: successfully pick up the kiwi from the table to the container"]
tasks: ["pick up the peg out of the stack and place it in to the hole"]

# robot + motion factory
motion_config: !include factory/components/motion_configs/fr3_with_franka_hand_ik.yaml
