# gym
# reset_arm_command: [3.69019823e-01,  1.99873044e-04,  3.64437265e-01,  9.99989858e-01,
#                     -2.65401198e-03, -1.43284955e-03,  3.34460145e-03]
# reset_space: "cartesian"
# robot + motion factory
motion_config: !include factory/components/motion_configs/right_fr3_with_pika_ati_ik.yaml
max_step_nums: 150 # for gym steps
step_frequency: 20 # gym interface step calling freq
action_type: "end_effector_pose"
# euler quaternion 6d_rotation
action_orientation_type: "euler"
# ee_pose mask 
observation_type: "ee_pose"
contain_ft: false
# relative delta
# chunk_action_mode: "relative"
use_relative_pose: true
is_debug: false

# collision related parameters
tool_wdith: 0.1
tool_thickness: 0.0255
# height_thresh: 0.02
height_thresh: 0.04

reset_space: "joint"
# z: 0.39570194
# [0.12914971577308007, -1.1414848191903935, -1.0206527956929927, -2.4291060833756553, -0.74327029123007, 1.9775413167802187, 0.32370524816915264]
reset_arm_command: [0.24926367185098658, -1.0425780090835255, -1.1887405299550489, -2.4203714233442803, -0.83565228390469, 2.045317454320303, 0.30392395819882406]
# now z: 0.32969364
reset_tool_command: [[1]]

tool_control_mode: "incremental"
tool_min: 0
tool_max: 1.1
tool_state_max: 90
# tool_control_mode: "binary"
# tool_open_thresh: 45
# tool_close_thresh: 45

enable_display: true
display_window_name: "pi0 client inference for umi data"
enable_plotting: false
enable_hardware: true

num_episodes: 8
max_timestamps: 1500
action_weight_mode: "uniform"
async_execution: false
infer_frequency: 10

# prompt guidance
# tasks: "pick up the blue cube and place it onto the top of red cube and then pick up the yellow cube and place it onto the blue cube"
# tasks: "pick up the peg out of the stack and put it into the hole"
# tasks: "grasp the right cup and pour it into the left cup"
# tasks: "collect a portion of rice with spoon and transfer it into the bowl"
# tasks: "grab the tube from the upper-left of the rack and insert it into the lower-right hole"
tasks: "pick up the kiwi fruit and place it into the red box"

