.git
.github
.venv
**/.git
**/.pytest_cache
**/.mypy_cache
**/__pycache__
**/*.pyc
**/*.pyo
**/*.swp
**/.DS_Store

dp_output

HirolPlatform/docs
HirolPlatform/docker
HirolPlatform/test
HirolPlatform/factory/test
HirolPlatform/dataset/analyze/out

