name: lcx-dp-inference

services:
  dp_inference:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   # args:
      #   UBUNTU_VERSION: ${UBUNTU_VERSION:-22.04}
      #   PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
      #   HOST_UID: ${UID:-1000}
      #   HOST_GID: ${GID:-1000}
      #   PANDA_PY_INSTALL_MODE: ${PANDA_PY_INSTALL_MODE:-source}
      #   PANDA_PY_VERSION: ${PANDA_PY_VERSION:-0.8.1}
      #   LIBFRANKA_VERSION: ${LIBFRANKA_VERSION:-0.15.0}
      #   PANDA_PY_GIT_REF: ${PANDA_PY_GIT_REF:-v0.8.1}
    image: lcx-dp:inferencev2
    user: teleophost
    network_mode: host
    command: ["bash", "-lc", "cd /workspace/HirolPlatform && tail -f /dev/null"]
    stdin_open: true
    privileged: true
    tty: true
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: ${XAUTHORITY:-$HOME/.Xauthority}
      MUJOCO_GL: osmesa
      MPLCONFIGDIR: /tmp/matplotlib
      WANDB_DIR: /workspace/wandb
      DP_HIROL_PATH: /workspace/dp_hirol-main
      PYTHONPATH: /workspace/HirolPlatform:/workspace/dp_hirol-main:/workspace
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics,video,display
      http_proxy:
      https_proxy:
      no_proxy:
    volumes:
      - ../HirolPlatform:/workspace/HirolPlatform
      - ../dp_hirol-main:/workspace/dp_hirol-main
      - ../dp_output:/workspace/dp_output
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${XAUTHORITY:-$HOME/.Xauthority}:${XAUTHORITY:-$HOME/.Xauthority}:ro
      - /sys/bus/usb:/sys/bus/usb:ro
      - /sys/class/input:/sys/class/input:ro
      - /dev:/dev
    devices:
      - /dev:/dev
      - /dev/bus/usb:/dev/bus/usb
      - /dev/input:/dev/input
      # - /var/run/dbus:/var/run/dbus
      # - /run/dbus:/run/dbus
    gpus: all
    group_add:
      - "plugdev"
      - "input"
      - "dialout"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, graphics, display, utility, video, compute]
