# gym
# robot + motion factory
motion_config: !include factory/components/motion_configs/right_fr3_with_das_ati_ik.yaml
max_step_nums: 150 # for gym steps
step_frequency: 20 # gym interface step calling freq
action_type: "end_effector_pose"
# euler quaternion 6d_rotation
action_orientation_type: "euler"
# ee_pose mask 
observation_type: "ee_pose"
img_resize_shape: [224, 224]
contain_ft: false
# relative delta
# chunk_action_mode: "relative"
use_relative_pose: true
is_debug: false

# collision related parameters
tool_wdith: 0.1
tool_thickness: 0.0255
# height_thresh: 0.01
height_thresh: 0.175

reset_tool_command: [[1]]

# transfer banana
# reset_arm_command: [0.4949421897203528, -1.567805829578173, -1.8572166701179154, -1.9905463709529319, 0.17777157010546682, 2.514054533859691, -1.230442816921196]
# reset_arm_command: [-0.0401738194832479, -1.5299874232993738, -1.9312359323737118, -2.4809956539881894, 0.0536879692413298, 2.5041080054362572, -1.2317390192072197]

# reset_arm_command: [0.5, -0.4, 0.1466055, 0.77337564, -0.01884924,  0.63362282, -0.00754556]

# [0.3, -0.5, 0.16026055, 0.7071068, 0, 0.7071068, 0]
# [0.5, -0.4, 0.1366055, 0.73920153, 0.02928333, 0.67255161, 0.01994781]
# absolute z: 0.27
reset_arm_command: [0.15327496, -0.54249998, 0.185, 0.7071068, 0, 0.7071068, 0]
# [0.15327496, -0.54249998, 0.2038416, 0.7071068, 0, 0.7071068, 0]
reset_space: "cartesian"

tool_control_mode: "incremental"
tool_min: 0
tool_max: 1.06
tool_state_max: 0.103
# tool_control_mode: "binary"
# tool_open_thresh: 45
# tool_close_thresh: 45

enable_display: true
display_window_name: "pi0 client inference for das data"
enable_plotting: false
enable_hardware: true

num_episodes: 100
max_timestamps: 6000
action_weight_mode: "no"
async_execution: false
action_weight_gain: 0.01
infer_frequency: 10

# teleoperation intervention
# tele_cfg: !include teleop/aruco_cube_tracker/config/cube_tracker_right_only_fr3_cfg.yaml
# tele_device: "cube_tracker"

# for data saving 
# data_save_path: "fr3_das_bread_picking_infer" # execution trajectory
# save_chunk_dir: "fr3_das_bread_picking_infer/action_chunks_fr3_absolute_color" # model infer action chunks
# model inference succ rate stats saving
# infer_stats_saving_dir: "dataset/data/ifner_stats_bp_das_fr3"

# prompt guidance
# tasks: "pick up the blue cube and place it onto the top of red cube and then pick up the yellow cube and place it onto the blue cube"
# tasks: "pick up the peg out of the stack and put it into the hole"
# tasks: "grasp the right cup and pour it into the left cup"
# tasks: "collect a portion of rice with spoon and transfer it into the bowl"
# tasks: "grab the tube from the upper-left of the rack and insert it into the lower-right hole"
# tasks: "pick up the kiwi fruit and place it into the red box"
# tasks: "transfer the banana from the yellow plate into the white plate"
tasks: "Pick up the bread on the right and place it on the white tray inside the container."
# tasks: "Pick up the tube on the right tube rack and insert to the left tube rack"
