fr3:
  initial_pose: [0.3, 0, 0, 1, 0, 0, 0]

duo_fr3:
  initial_pose_left: [0.3, 0.3, -0.4, 1, 0, 0, 0]
  initial_pose_right: [0.3, -0.08, -0.4, 1, 0, 0, 0]
    
unitree:
  initial_pose_left: [0.26, 0.15, 0.9, 0, 0, 0, 1]
  initial_pose_right: [0.26, -0.15, 0.9, 0, 0, 0, 1]

agibot:
  # for standing, if you are siting set z to be 0.35/0.4
  initial_pose_left: [0.65, 0.2, 0.25, 0, 0.7071068, 0.7071068, 0]
  initial_pose_right: [0.65, -0.2, 0.25, 0, -0.7071068, 0.7071068, 0]

XR:
  openxr_robot: [-0.5, 0.5, 0.5, 0.5, 0, 0, 0, 1]
    