# usage platform
use_hardware: false
use_simulation: true

robot: "duo_arm"
robot_config: !include hardware/config/duo_xarm_cfg.yaml
gripper: "duo_tool"
gripper_config: !include hardware/config/duo_xarm_gripper_cfg.yaml

# sensor infos
sensor_dicts:
  cameras:
    # - name: "left_ee_cam"
    #   type: "realsense_camera"
    #   cfg: !include hardware/sensors/cameras/config
    # - name: "right_ee_cam"
    #   type: "realsense_camera"
    #   cfg: !include hardware/sensors/cameras/config
    - name: "third_person_cam"
      type: "obec_camera"
      cfg: !include hardware/sensors/cameras/config/obec_cfg.yaml

control_frequency: 100
controller_type: "duo_controller"
controller_config: 
  - type: "left"
    name: "ik"
    cfg: !include controller/config/ik_fr3_cfg.yaml
  - type: "right"
    name: "ik"
    cfg: !include controller/config/ik_fr3_cfg.yaml

model_type: "duo_model"
model_config: 
  - type: "left"
    name: "fr3_franka_hand"
    cfg: !include motion/config/robot_model_fr3_cfg.yaml
  - type: "right"
    name: "fr3_franka_hand"
    cfg: !include motion/config/robot_model_fr3_cfg.yaml

buffer_type: "duo_buffer"
trajectory_planner_type: "cart_polynomial"
plan_type: "cartesian"
trajectory_config: !include trajectory/config/cartesian_polynomial_traj_cfg.yaml
traj_frequency: 450

teleop_interface: "meta_quest3"
interface_config: !include teleop/XR/quest3/config/meta_quest3_duo_fr3.yaml
inteface_output_mode: "absolute"

simulation: "mujoco"
simulation_config: !include simulation/config/mujoco_duo_fr3.yaml
target_site_name: ["targetL_site", "targetR_site"]
tcp_visualization_site: ["TCPL_site", "TCPR_site"]

# teleoperation used parameter
use_trajectory_planner: false
# if you are using mujoco simulation target instead of teleoperation device,
# set use_simulation_target as true
use_simulation_target: false
teleoperation_loop_time: 0.01
