pika_config: !include teleop/pika_tracker/config/pika_as_umi_wo_head_cfg.yaml
pika_mode: "absolute_delta"
use_fisheye: true
cameras:
  - name: "left_hand"
    type: "realsense_camera"
    config: !include hardware/sensors/cameras/config/left_pika_sense_d405_cfg.yaml
  - name: "right_hand"
    type: "realsense_camera" 
    config: !include hardware/sensors/cameras/config/right_pika_sense_d405_cfg.yaml
  - name: "left_hand_fisheye"
    type: "opencv_camera"
    config: !include hardware/sensors/cameras/config/left_pika_sense_fisheye_cfg.yaml
  - name: "right_hand_fisheye"
    type: "opencv_camera"
    config: !include hardware/sensors/cameras/config/right_pika_sense_fisheye_cfg.yaml

collection_frequency: 30
task_name: "duo_fr3_wo_head_pick_n_place"
use_mujoco: true
