motion_config: !include factory/components/motion_configs/agibot_g1_wbik.yaml

teleop_interface: "meta_quest3"
interface_config: !include teleop/xr/meta_quest3_cfg.yaml
inteface_output_mode: "absolute_delta"

target_site_name: ["targetL_site", "targetL_site"]
tcp_visualization_site: ["TCPL_site", "TCPR_site"]
# teleoperation used parameter
# if you are using mujoco simulation target instead of teleoperation device,
# set use_simulation_target as true
use_simulation_target: true
teleoperation_loop_time: 0.005
