# robot + motion factory
motion_config: !include factory/components/motion_configs/left_fr3_with_pika_ati_ik.yaml
max_step_nums: 150 # for gym steps
# end_effector_pose_delta joint_position
action_type: "end_effector_pose_delta"
# euler quaternion
action_orientation_type: "euler"
# joint_position ee_pose joint_position_ee_pose mask delta_ee_pose
observation_type: "delta_ee_pose"
is_debug: false

reset_space: "joint"
# reset_arm_command: [-0.0016708960744338654, -0.7861180279768628, 
#                       0.0011242960248884306, -2.3515749674770583, 
#                       -0.0019059956649008665, 1.581831610375827, 
#                       0.7904221443917989]
reset_tool_command: [[1]]

tool_control_mode: "incremental"
tool_min: 0
tool_max: 90
# tool_control_mode: "binary"
# tool_open_thresh: 45
# tool_close_thresh: 45

enable_display: true
display_window_name: "mlp bc inference"
enable_plotting: false
enable_hardware: true

num_episodes: 8
max_timestamps: 1500
execution_chunk_steps: 35
action_weight_mode: "no"
action_weight_gain: -0.01
async_execution: false

device: "cuda:0"
img_shape: [224, 224]
model_dir: "/mnt/nas/zyx_checkpoints/mlp_bc/fr3/1104/ckpts/1025_pick_n_place_de2de/bc_epoch900.pt"
data_dir: "/mnt/nas/zyx_checkpoints/mlp_bc/fr3/1104/ckpts/1025_pick_n_place_de2de/data_stats.json"
