control_dt: 0.002

hand: !include dex3.yaml

# urdf_path: "assets/unitree_g1/g1_29dof_with_hand.urdf"
urdf_path: "assets/unitree_g1/g1_29dof_lock_waist_with_hand_rev_1_0.urdf"

joint_names_left: ["left_shoulder_pitch_joint",
              "left_shoulder_roll_joint",
              "left_shoulder_yaw_joint", 
              "left_elbow_joint", 
              "left_wrist_roll_joint",
              "left_wrist_pitch_joint",
              "left_wrist_yaw_joint"]

joint_names_right: ["right_shoulder_pitch_joint",
              "right_shoulder_roll_joint",
              "right_shoulder_yaw_joint", 
              "right_elbow_joint", 
              "right_wrist_roll_joint",
              "right_wrist_pitch_joint",
              "right_wrist_yaw_joint"]