unitree_g1:
  dof: [7, 7]  # Dual arm DOF configuration
  network_interface: "enp5s0"
  enable_low_level: false
  control_frequency: 500
  update_frequency: 800
  ankle_mode: "pr" # pr or ab
  control_mode: "position"
  